---
- name: Check Kubernetes jobs
  hosts: kubernetes_control_plane[0]
  become: true
  gather_facts: false

  roles:
    - role: ../roles/k8s_checks
      tags:
        - kubernetes
        - checks
