---
- import_playbook: prepare_tools.yml
  tags:
    - prepare_tools

- import_playbook: check_os.yml
  tags:
    - os
    - checks

- import_playbook: check_kubernetes.yml
  tags:
    - kubernetes
    - checks

- import_playbook: format_report.yml
  tags:
    - report
